//
// ApiError.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** \u9519\u8BEF\u4FE1\u606F */
public class ApiError: JSONEncodable {

    public var errCode: Int?
    public var errMsg: String?
    

    public init() {}

    // MARK: JSONEncodable
    func encodeToJSON() -> AnyObject {
        var nillableDictionary = [String:AnyObject?]()
        nillableDictionary["errCode"] = self.errCode
        nillableDictionary["errMsg"] = self.errMsg
        let dictionary: [String:AnyObject] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
