//
// App.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


public class App: JSONEncodable {

    /** \u90AE\u4EF6\u6A21\u677F\u7F16\u53F7 */
    public var emailTemplateId: String?
    /** Signature completed redirected link */
    public var redirectUri: String?
    /** \u5370\u7AE0\u91C7\u96C6H5\u9875\u9762\u6A21\u677F\u7F16\u53F7 */
    public var sealHtml5TemplateId: String?
    /** \u7B7E\u540D\u91C7\u96C6H5\u9875\u9762\u6A21\u677F\u7F16\u53F7 */
    public var signatureHtml5TemplateId: String?
    /** \u77ED\u4FE1\u6A21\u677F\u7F16\u53F7 */
    public var smsTemplateId: String?
    

    public init() {}

    // MARK: JSONEncodable
    func encodeToJSON() -> AnyObject {
        var nillableDictionary = [String:AnyObject?]()
        nillableDictionary["emailTemplateId"] = self.emailTemplateId
        nillableDictionary["redirectUri"] = self.redirectUri
        nillableDictionary["sealHtml5TemplateId"] = self.sealHtml5TemplateId
        nillableDictionary["signatureHtml5TemplateId"] = self.signatureHtml5TemplateId
        nillableDictionary["smsTemplateId"] = self.smsTemplateId
        let dictionary: [String:AnyObject] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
