//
// Company.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** \u5355\u4F4D\u4FE1\u606F */
public class Company: JSONEncodable {

    /** \u662F\u5426\u90AE\u4EF6\u901A\u77E5\u7B7E\u7F72\u4EBA(y/n) */
    public var emailNotice: String?
    /** \u9886\u7B7E\u7CFB\u7EDF\u7528\u6237\u7F16\u53F7 */
    public var linksignUserId: String?
    /** \u5355\u4F4D\u6388\u6743\u4EBA\u90AE\u7BB1 */
    public var orgAuthorizerEmail: String?
    /** \u5355\u4F4D\u6388\u6743\u4EBA\u8BC1\u4EF6\u53F7\u7801 */
    public var orgAuthorizerIdcardNumber: String?
    /** \u5355\u4F4D\u6388\u6743\u4EBA\u8BC1\u4EF6\u7C7B\u578B */
    public var orgAuthorizerIdcardType: String?
    /** \u5355\u4F4D\u6388\u6743\u4EBA\u59D3\u540D */
    public var orgAuthorizerName: String?
    public var orgAuthorizerPhone: String?
    /** \u5355\u4F4D\u8BC1\u4EF6\u7F16\u53F7 */
    public var orgIdcardNumber: String?
    /** \u5355\u4F4D\u8BC1\u4EF6\u7C7B\u578B */
    public var orgIdcardType: String?
    /** \u5355\u4F4D\u540D\u79F0 */
    public var orgName: String?
    /** \u516C\u53F8\u7D22\u5F15 */
    public var recipientIndex: String?
    /** \u662F\u5426\u77ED\u4FE1\u901A\u77E5\u7B7E\u7F72\u4EBA(y/n) */
    public var smsNotice: String?
    

    public init() {}

    // MARK: JSONEncodable
    func encodeToJSON() -> AnyObject {
        var nillableDictionary = [String:AnyObject?]()
        nillableDictionary["emailNotice"] = self.emailNotice
        nillableDictionary["linksignUserId"] = self.linksignUserId
        nillableDictionary["orgAuthorizerEmail"] = self.orgAuthorizerEmail
        nillableDictionary["orgAuthorizerIdcardNumber"] = self.orgAuthorizerIdcardNumber
        nillableDictionary["orgAuthorizerIdcardType"] = self.orgAuthorizerIdcardType
        nillableDictionary["orgAuthorizerName"] = self.orgAuthorizerName
        nillableDictionary["orgAuthorizerPhone"] = self.orgAuthorizerPhone
        nillableDictionary["orgIdcardNumber"] = self.orgIdcardNumber
        nillableDictionary["orgIdcardType"] = self.orgIdcardType
        nillableDictionary["orgName"] = self.orgName
        nillableDictionary["recipientIndex"] = self.recipientIndex
        nillableDictionary["smsNotice"] = self.smsNotice
        let dictionary: [String:AnyObject] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
