//
// DocumentSummary.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** \u6587\u6863\u7B7E\u7F72\u7ED3\u679C */
public class DocumentSummary: JSONEncodable {

    /** \u7B7E\u7F72\u540E\u7684\u6587\u6863\u7F16\u53F7 */
    public var documentId: String?
    public var documentStatus: DocumentStatus?
    /** \u7B7E\u7F72\u540E\u7684\u6587\u6863\u4E0B\u8F7D\u94FE\u63A5 */
    public var uri: String?
    

    public init() {}

    // MARK: JSONEncodable
    func encodeToJSON() -> AnyObject {
        var nillableDictionary = [String:AnyObject?]()
        nillableDictionary["documentId"] = self.documentId
        nillableDictionary["documentStatus"] = self.documentStatus?.encodeToJSON()
        nillableDictionary["uri"] = self.uri
        let dictionary: [String:AnyObject] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
