//
// DocumentStatus.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


public class DocumentStatus: JSONEncodable {

    public var companySignerStatus: [SignerStatus]?
    public var personalSignerStatus: [SignerStatus]?
    /** Document status (  signing, signed) */
    public var status: String?
    

    public init() {}

    // MARK: JSONEncodable
    func encodeToJSON() -> AnyObject {
        var nillableDictionary = [String:AnyObject?]()
        nillableDictionary["companySignerStatus"] = self.companySignerStatus?.encodeToJSON()
        nillableDictionary["personalSignerStatus"] = self.personalSignerStatus?.encodeToJSON()
        nillableDictionary["status"] = self.status
        let dictionary: [String:AnyObject] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
