//
// Document.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** \u7B7E\u7F72\u6587\u6863\u4FE1\u606F */
public class Document: JSONEncodable {

    /** \u6587\u6863\u5185\u5BB9\uFF08Base64\u683C\u5F0F\uFF09 */
    public var documentBase64: String?
    /** \u6587\u6863\u7D22\u5F15\uFF0C\u4E0ESignHere\u5BF9\u5E94 */
    public var documentIndex: String?
    /** \u6587\u6863\u540E\u7F00\uFF08\u683C\u5F0F\uFF09 */
    public var fileExtension: String?
    /** \u6587\u6863\u540D\u79F0 */
    public var name: String?
    

    public init() {}

    // MARK: JSONEncodable
    func encodeToJSON() -> AnyObject {
        var nillableDictionary = [String:AnyObject?]()
        nillableDictionary["documentBase64"] = self.documentBase64
        nillableDictionary["documentIndex"] = self.documentIndex
        nillableDictionary["fileExtension"] = self.fileExtension
        nillableDictionary["name"] = self.name
        let dictionary: [String:AnyObject] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
