//
// DocumentDefinition.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** \u7B7E\u7F72\u6587\u6863\u5B9A\u4E49 */
public class DocumentDefinition: JSONEncodable {

    /** Application configuration */
    public var app: App?
    /** \u81EA\u5B9A\u4E49\u5B57\u6BB5 */
    public var customFields: CustomFields?
    /** \u5F85\u7B7E\u7F72\u7684\u6587\u6863\u5217\u8868 */
    public var documents: [Document]?
    /** \u5176\u5B83\u63A5\u6536\u4EBA */
    public var extraRecipients: ExtraRecipients?
    /** Signature authentication */
    public var idAuth: IdAuth?
    /** \u7B7E\u7F72\u4EBA */
    public var signers: Signers?
    /** Custom template number */
    public var templateId: String?
    

    public init() {}

    // MARK: JSONEncodable
    func encodeToJSON() -> AnyObject {
        var nillableDictionary = [String:AnyObject?]()
        nillableDictionary["app"] = self.app?.encodeToJSON()
        nillableDictionary["customFields"] = self.customFields?.encodeToJSON()
        nillableDictionary["documents"] = self.documents?.encodeToJSON()
        nillableDictionary["extraRecipients"] = self.extraRecipients?.encodeToJSON()
        nillableDictionary["idAuth"] = self.idAuth?.encodeToJSON()
        nillableDictionary["signers"] = self.signers?.encodeToJSON()
        nillableDictionary["templateId"] = self.templateId
        let dictionary: [String:AnyObject] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
