//
// EmailRecipient.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** \u90AE\u4EF6\u63A5\u6536\u8005\u4FE1\u606F */
public class EmailRecipient: JSONEncodable {

    /** \u79D8\u5BC6\u6284\u9001\uFF08y/n\uFF09 */
    public var bcc: String?
    /** \u90AE\u4EF6\u5730\u5740 */
    public var emailAddress: String?
    /** \u59D3\u540D */
    public var name: String?
    

    public init() {}

    // MARK: JSONEncodable
    func encodeToJSON() -> AnyObject {
        var nillableDictionary = [String:AnyObject?]()
        nillableDictionary["bcc"] = self.bcc
        nillableDictionary["emailAddress"] = self.emailAddress
        nillableDictionary["name"] = self.name
        let dictionary: [String:AnyObject] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
