//
// IdAuth.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** Signature identity authentication */
public class IdAuth: JSONEncodable {

    /** ***true***,***false*** */
    public var bankAccountRequred: String?
    /** ***true***,***false*** */
    public var emailRequred: String?
    /** ***true***,***false*** */
    public var faceCompareRequred: String?
    /** ***true***,***false*** */
    public var idNumberRequred: String?
    /** ***true***,***false*** */
    public var smsRequred: String?
    /** *** true ***,***false*** */
    public var wechatRequred: String?
    

    public init() {}

    // MARK: JSONEncodable
    func encodeToJSON() -> AnyObject {
        var nillableDictionary = [String:AnyObject?]()
        nillableDictionary["bankAccountRequred"] = self.bankAccountRequred
        nillableDictionary["emailRequred"] = self.emailRequred
        nillableDictionary["faceCompareRequred"] = self.faceCompareRequred
        nillableDictionary["idNumberRequred"] = self.idNumberRequred
        nillableDictionary["smsRequred"] = self.smsRequred
        nillableDictionary["wechatRequred"] = self.wechatRequred
        let dictionary: [String:AnyObject] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
