//
// ImageCustomField.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** Custom fields for image type */
public class ImageCustomField: JSONEncodable {

    /** Custom field id */
    public var fieldId: String?
    /** Base64 image file format */
    public var imageBase64: String?
    /** user seal ID */
    public var sealId: String?
    /** user signature ID */
    public var signatureId: String?
    

    public init() {}

    // MARK: JSONEncodable
    func encodeToJSON() -> AnyObject {
        var nillableDictionary = [String:AnyObject?]()
        nillableDictionary["fieldId"] = self.fieldId
        nillableDictionary["imageBase64"] = self.imageBase64
        nillableDictionary["sealId"] = self.sealId
        nillableDictionary["signatureId"] = self.signatureId
        let dictionary: [String:AnyObject] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
