//
// Personal.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** \u4E2A\u4EBA\u4FE1\u606F */
public class Personal: JSONEncodable {

    /** \u662F\u5426\u90AE\u4EF6\u901A\u77E5\u7B7E\u7F72\u4EBA(y/n) */
    public var emailNotice: String?
    /** \u9886\u7B7E\u7CFB\u7EDF\u7528\u6237\u7F16\u53F7 */
    public var linksignUserId: String?
    public var personEmail: String?
    public var personIdcardNumber: String?
    public var personIdcardType: String?
    public var personName: String?
    public var personOrgName: String?
    public var personPhone: String?
    /** \u4E2A\u4EBA\u7D22\u5F15 */
    public var recipientIndex: String?
    /** \u662F\u5426\u77ED\u4FE1\u901A\u77E5\u7B7E\u7F72\u4EBA(y/n) */
    public var smsNotice: String?
    

    public init() {}

    // MARK: JSONEncodable
    func encodeToJSON() -> AnyObject {
        var nillableDictionary = [String:AnyObject?]()
        nillableDictionary["emailNotice"] = self.emailNotice
        nillableDictionary["linksignUserId"] = self.linksignUserId
        nillableDictionary["personEmail"] = self.personEmail
        nillableDictionary["personIdcardNumber"] = self.personIdcardNumber
        nillableDictionary["personIdcardType"] = self.personIdcardType
        nillableDictionary["personName"] = self.personName
        nillableDictionary["personOrgName"] = self.personOrgName
        nillableDictionary["personPhone"] = self.personPhone
        nillableDictionary["recipientIndex"] = self.recipientIndex
        nillableDictionary["smsNotice"] = self.smsNotice
        let dictionary: [String:AnyObject] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
