//
// Seal.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** \u5370\u7AE0\u4FE1\u606F */
public class Seal: JSONEncodable {

    public var company: Company?
    /** \u6536\u96C6\u5B8C\u6210\u540E\u8DF3\u8F6C\u7684\u5E94\u7528URI */
    public var redirectUri: String?
    /** \u4E0E\u5370\u7AE0\u5173\u8054\u7684\u7B7E\u540D\u7F16\u53F7 */
    public var relateSignatureId: String?
    

    public init() {}

    // MARK: JSONEncodable
    func encodeToJSON() -> AnyObject {
        var nillableDictionary = [String:AnyObject?]()
        nillableDictionary["Company"] = self.company?.encodeToJSON()
        nillableDictionary["redirectUri"] = self.redirectUri
        nillableDictionary["relateSignatureId"] = self.relateSignatureId
        let dictionary: [String:AnyObject] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
