//
// Signature.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** \u7B7E\u540D */
public class Signature: JSONEncodable {

    /** \u4E2A\u4EBA\u4FE1\u606F */
    public var personal: Personal?
    /** \u6536\u96C6\u5B8C\u6210\u540E\u8DF3\u8F6C\u7684\u5E94\u7528URI */
    public var redirectUri: String?
    /** \u4E0E\u7B7E\u540D\u5173\u8054\u7684\u5370\u7AE0\u7F16\u53F7 */
    public var relateSealId: String?
    

    public init() {}

    // MARK: JSONEncodable
    func encodeToJSON() -> AnyObject {
        var nillableDictionary = [String:AnyObject?]()
        nillableDictionary["Personal"] = self.personal?.encodeToJSON()
        nillableDictionary["redirectUri"] = self.redirectUri
        nillableDictionary["relateSealId"] = self.relateSealId
        let dictionary: [String:AnyObject] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
