//
// SignDateTime.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** \u7B7E\u7F72\u65F6\u95F4\u4FE1\u606F */
public class SignDateTime: JSONEncodable {

    /** \u65F6\u95F4\u663E\u793A\u683C\u5F0F */
    public var dateTimePattern: String?
    /** \u6587\u6863\u7D22\u5F15 */
    public var documentIndex: String?
    /** \u5B57\u4F53\u540D\u79F0 */
    public var fontName: String?
    /** \u5B57\u4F53\u5927\u5C0F */
    public var fontSize: Float?
    /** \u9875\u7801 */
    public var pageNumber: Int?
    /** \u7B7E\u7F72\u4EBA\u7D22\u5F15\u53F7 */
    public var recipientIndex: String?
    /** \u6A21\u677F\u65F6\u95F4\u5B57\u6BB5\u540D */
    public var templateDateFieldId: String?
    /** \u5BBD\u5EA6 */
    public var width: Int?
    /** X\u5750\u6807 */
    public var xPosition: Int?
    /** Y\u5750\u6807 */
    public var yPosition: Int?
    

    public init() {}

    // MARK: JSONEncodable
    func encodeToJSON() -> AnyObject {
        var nillableDictionary = [String:AnyObject?]()
        nillableDictionary["dateTimePattern"] = self.dateTimePattern
        nillableDictionary["documentIndex"] = self.documentIndex
        nillableDictionary["fontName"] = self.fontName
        nillableDictionary["fontSize"] = self.fontSize
        nillableDictionary["pageNumber"] = self.pageNumber
        nillableDictionary["recipientIndex"] = self.recipientIndex
        nillableDictionary["templateDateFieldId"] = self.templateDateFieldId
        nillableDictionary["width"] = self.width
        nillableDictionary["xPosition"] = self.xPosition
        nillableDictionary["yPosition"] = self.yPosition
        let dictionary: [String:AnyObject] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
