//
// SignHere.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** \u7B7E\u7F72\u4F4D\u7F6E\u4FE1\u606F */
public class SignHere: JSONEncodable {

    /** \u7B7E\u540D\u6587\u4EF6\u7D22\u5F15\uFF0C \u4E0EDocument\u5BF9\u5E94 */
    public var documentIndex: String?
    /** \u7B7E\u7F72\u533A\u57DF\u9AD8\u5EA6 */
    public var height: Int?
    public var pageNumber: Int?
    /** \u7B7E\u7F72\u4EBA\u7D22\u5F15 */
    public var recipientIndex: String?
    /** \u5370\u7AE0\u9AD8\u5EA6 */
    public var sealHeight: Int?
    /** \u5370\u7AE0\u7F16\u53F7 */
    public var sealId: String?
    /** \u5370\u7AE0\u9875\u7801 */
    public var sealPageNumber: Int?
    /** \u5370\u7AE0\u5BBD\u5EA6 */
    public var sealWidth: Int?
    /** \u5370\u7AE0X\u5750\u6807 */
    public var sealXPosition: Int?
    /** \u5370\u7AE0Y\u5750\u6807 */
    public var sealYPosition: Int?
    /** \u7B7E\u540D\u7F16\u53F7 */
    public var signatureId: String?
    /** \u6A21\u677F\u516C\u7AE0\u5B57\u6BB5\u540D */
    public var templateSealFieldId: String?
    /** \u6A21\u677F\u7B7E\u540D\u5B57\u6BB5\u540D */
    public var templateSignatureFieldId: String?
    /** \u7B7E\u540D\u57DF\u5BBD\u5EA6 */
    public var width: Int?
    /** x\u5750\u6807 */
    public var xPosition: Int?
    /** y\u5750\u6807 */
    public var yPosition: Int?
    

    public init() {}

    // MARK: JSONEncodable
    func encodeToJSON() -> AnyObject {
        var nillableDictionary = [String:AnyObject?]()
        nillableDictionary["documentIndex"] = self.documentIndex
        nillableDictionary["height"] = self.height
        nillableDictionary["pageNumber"] = self.pageNumber
        nillableDictionary["recipientIndex"] = self.recipientIndex
        nillableDictionary["sealHeight"] = self.sealHeight
        nillableDictionary["sealId"] = self.sealId
        nillableDictionary["sealPageNumber"] = self.sealPageNumber
        nillableDictionary["sealWidth"] = self.sealWidth
        nillableDictionary["sealXPosition"] = self.sealXPosition
        nillableDictionary["sealYPosition"] = self.sealYPosition
        nillableDictionary["signatureId"] = self.signatureId
        nillableDictionary["templateSealFieldId"] = self.templateSealFieldId
        nillableDictionary["templateSignatureFieldId"] = self.templateSignatureFieldId
        nillableDictionary["width"] = self.width
        nillableDictionary["xPosition"] = self.xPosition
        nillableDictionary["yPosition"] = self.yPosition
        let dictionary: [String:AnyObject] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
