//
// SignatureSummary.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


public class SignatureSummary: JSONEncodable {

    public var signatureFileUri: String?
    public var signatureId: String?
    public var signerRedirectUri: String?
    

    public init() {}

    // MARK: JSONEncodable
    func encodeToJSON() -> AnyObject {
        var nillableDictionary = [String:AnyObject?]()
        nillableDictionary["signatureFileUri"] = self.signatureFileUri
        nillableDictionary["signatureId"] = self.signatureId
        nillableDictionary["signerRedirectUri"] = self.signerRedirectUri
        let dictionary: [String:AnyObject] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
