//
// Signers.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


public class Signers: JSONEncodable {

    /** \u7B7E\u7F72\u4EBA\u5217\u8868\uFF08\u516C\u53F8\uFF09 */
    public var signerCompanys: [Company]?
    /** \u7B7E\u7F72\u4EBA\u5217\u8868\uFF08\u4E2A\u4EBA\uFF09 */
    public var signerPersons: [Personal]?
    /** \u7B7E\u7F72\u4FE1\u606F\u9762\u677F */
    public var tabs: Tabs?
    

    public init() {}

    // MARK: JSONEncodable
    func encodeToJSON() -> AnyObject {
        var nillableDictionary = [String:AnyObject?]()
        nillableDictionary["signerCompanys"] = self.signerCompanys?.encodeToJSON()
        nillableDictionary["signerPersons"] = self.signerPersons?.encodeToJSON()
        nillableDictionary["tabs"] = self.tabs?.encodeToJSON()
        let dictionary: [String:AnyObject] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
