//
// SmsRecipient.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** \u77ED\u4FE1\u63A5\u6536\u8005\u4FE1\u606F */
public class SmsRecipient: JSONEncodable {

    /** \u624B\u673A\u53F7\u7801 */
    public var mobile: String?
    /** \u59D3\u540D */
    public var name: String?
    

    public init() {}

    // MARK: JSONEncodable
    func encodeToJSON() -> AnyObject {
        var nillableDictionary = [String:AnyObject?]()
        nillableDictionary["mobile"] = self.mobile
        nillableDictionary["name"] = self.name
        let dictionary: [String:AnyObject] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
