//
// Tabs.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** \u7B7E\u7F72\u76F8\u5173\u4FE1\u606F */
public class Tabs: JSONEncodable {

    /** \u7B7E\u7F72\u65F6\u95F4\u4FE1\u606F */
    public var dateTabs: [SignDateTime]?
    public var signHereTabs: [SignHere]?
    

    public init() {}

    // MARK: JSONEncodable
    func encodeToJSON() -> AnyObject {
        var nillableDictionary = [String:AnyObject?]()
        nillableDictionary["dateTabs"] = self.dateTabs?.encodeToJSON()
        nillableDictionary["signHereTabs"] = self.signHereTabs?.encodeToJSON()
        let dictionary: [String:AnyObject] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
