//
// TextCustomField.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** \u81EA\u5B9A\u4E49\u5B57\u6BB5 */
public class TextCustomField: JSONEncodable {

    /** \u7528\u6237\u81EA\u5B9A\u4E49\u7684\u5B57\u6BB5\u7F16\u53F7 */
    public var fieldId: String?
    /** \u5185\u5BB9 */
    public var value: String?
    

    public init() {}

    // MARK: JSONEncodable
    func encodeToJSON() -> AnyObject {
        var nillableDictionary = [String:AnyObject?]()
        nillableDictionary["fieldId"] = self.fieldId
        nillableDictionary["value"] = self.value
        let dictionary: [String:AnyObject] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
