//
// WechatRecipient.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** \u5FAE\u4FE1\u63A5\u6536\u8005\u4FE1\u606F */
public class WechatRecipient: JSONEncodable {

    /** \u59D3\u540D */
    public var name: String?
    /** \u516C\u4F17\u53F7\u552F\u4E00\u6807\u8BC6 */
    public var openId: String?
    

    public init() {}

    // MARK: JSONEncodable
    func encodeToJSON() -> AnyObject {
        var nillableDictionary = [String:AnyObject?]()
        nillableDictionary["name"] = self.name
        nillableDictionary["openId"] = self.openId
        let dictionary: [String:AnyObject] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
