//
// DocumentAPI.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Alamofire



public class DocumentAPI: APIBase {
    /**
     
     \u83B7\u53D6\u6587\u4EF6\u7B7E\u7F72\u72B6\u6001\u3001URI
     
     - parameter clientId: (path)  
     - parameter documentId: (path)  
     - parameter completion: completion handler to receive the data and the error objects
     */
    public class func clientsClientIdDocumentsDocumentIdStatusGet(clientId clientId: String, documentId: String, completion: ((data: DocumentStatus?, error: ErrorType?) -> Void)) {
        clientsClientIdDocumentsDocumentIdStatusGetWithRequestBuilder(clientId: clientId, documentId: documentId).execute { (response, error) -> Void in
            completion(data: response?.body, error: error);
        }
    }


    /**
     
     \u83B7\u53D6\u6587\u4EF6\u7B7E\u7F72\u72B6\u6001\u3001URI
     
     - GET /clients/{clientId}/documents/{documentId}/status
     - examples: [{example={
  "status" : "aeiou",
  "personalSignerStatus" : [ "" ],
  "companySignerStatus" : [ {
    "status" : "aeiou",
    "recipientIndex" : "aeiou",
    "signerUri" : "aeiou"
  } ]
}, contentType=application/json}]
     
     - parameter clientId: (path)  
     - parameter documentId: (path)  

     - returns: RequestBuilder<DocumentStatus> 
     */
    public class func clientsClientIdDocumentsDocumentIdStatusGetWithRequestBuilder(clientId clientId: String, documentId: String) -> RequestBuilder<DocumentStatus> {
        var path = "/clients/{clientId}/documents/{documentId}/status"
        path = path.stringByReplacingOccurrencesOfString("{clientId}", withString: "\(clientId)", options: .LiteralSearch, range: nil)
        path = path.stringByReplacingOccurrencesOfString("{documentId}", withString: "\(documentId)", options: .LiteralSearch, range: nil)
        let URLString = SwaggerClientAPI.basePath + path
        
        let nillableParameters: [String:AnyObject?] = [:]
        let parameters = APIHelper.rejectNil(nillableParameters)

        let requestBuilder: RequestBuilder<DocumentStatus>.Type = SwaggerClientAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "GET", URLString: URLString, parameters: parameters, isBody: true)
    }

    /**
     
     \u7B7E\u7F72\u6587\u4EF6
     
     - parameter clientId: (path)  
     - parameter body: (body)  (optional)
     - parameter completion: completion handler to receive the data and the error objects
     */
    public class func createDocument(clientId clientId: String, body: DocumentDefinition?, completion: ((data: DocumentSummary?, error: ErrorType?) -> Void)) {
        createDocumentWithRequestBuilder(clientId: clientId, body: body).execute { (response, error) -> Void in
            completion(data: response?.body, error: error);
        }
    }


    /**
     
     \u7B7E\u7F72\u6587\u4EF6
     
     - POST /clients/{clientId}/documents
     - \u7B7E\u7F72\u6587\u4EF6
     - examples: [{example={
  "uri" : "aeiou",
  "documentStatus" : {
    "status" : "aeiou",
    "personalSignerStatus" : [ "" ],
    "companySignerStatus" : [ {
      "status" : "aeiou",
      "recipientIndex" : "aeiou",
      "signerUri" : "aeiou"
    } ]
  },
  "documentId" : "aeiou"
}, contentType=application/json}]
     
     - parameter clientId: (path)  
     - parameter body: (body)  (optional)

     - returns: RequestBuilder<DocumentSummary> 
     */
    public class func createDocumentWithRequestBuilder(clientId clientId: String, body: DocumentDefinition?) -> RequestBuilder<DocumentSummary> {
        var path = "/clients/{clientId}/documents"
        path = path.stringByReplacingOccurrencesOfString("{clientId}", withString: "\(clientId)", options: .LiteralSearch, range: nil)
        let URLString = SwaggerClientAPI.basePath + path
        
        let parameters = body?.encodeToJSON() as? [String:AnyObject]

        let requestBuilder: RequestBuilder<DocumentSummary>.Type = SwaggerClientAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "POST", URLString: URLString, parameters: parameters, isBody: true)
    }

    /**
     
     \u83B7\u53D6\u6587\u4EF6
     
     - parameter clientId: (path)  
     - parameter documentId: (path)  
     - parameter completion: completion handler to receive the data and the error objects
     */
    public class func getDocument(clientId clientId: String, documentId: String, completion: ((data: NSURL?, error: ErrorType?) -> Void)) {
        getDocumentWithRequestBuilder(clientId: clientId, documentId: documentId).execute { (response, error) -> Void in
            completion(data: response?.body, error: error);
        }
    }


    /**
     
     \u83B7\u53D6\u6587\u4EF6
     
     - GET /clients/{clientId}/documents/{documentId}
     - \u83B7\u53D6\u6587\u4EF6
     - examples: [{output=none}]
     
     - parameter clientId: (path)  
     - parameter documentId: (path)  

     - returns: RequestBuilder<NSURL> 
     */
    public class func getDocumentWithRequestBuilder(clientId clientId: String, documentId: String) -> RequestBuilder<NSURL> {
        var path = "/clients/{clientId}/documents/{documentId}"
        path = path.stringByReplacingOccurrencesOfString("{clientId}", withString: "\(clientId)", options: .LiteralSearch, range: nil)
        path = path.stringByReplacingOccurrencesOfString("{documentId}", withString: "\(documentId)", options: .LiteralSearch, range: nil)
        let URLString = SwaggerClientAPI.basePath + path
        
        let nillableParameters: [String:AnyObject?] = [:]
        let parameters = APIHelper.rejectNil(nillableParameters)

        let requestBuilder: RequestBuilder<NSURL>.Type = SwaggerClientAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "GET", URLString: URLString, parameters: parameters, isBody: true)
    }

}
