//
// SignatureAPI.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Alamofire



public class SignatureAPI: APIBase {
    /**
     
     \u65B0\u5EFA\u4E00\u4E2A\u7B7E\u540D\u6536\u96C6\u8BF7\u6C42
     
     - parameter clientId: (path) \u5BA2\u6237\u7F16\u53F7 
     - parameter body: (body)  (optional)
     - parameter completion: completion handler to receive the data and the error objects
     */
    public class func createSignature(clientId clientId: String, body: Signature?, completion: ((data: SignatureSummary?, error: ErrorType?) -> Void)) {
        createSignatureWithRequestBuilder(clientId: clientId, body: body).execute { (response, error) -> Void in
            completion(data: response?.body, error: error);
        }
    }


    /**
     
     \u65B0\u5EFA\u4E00\u4E2A\u7B7E\u540D\u6536\u96C6\u8BF7\u6C42
     
     - POST /clients/{clientId}/signatures
     - \u65B0\u5EFA\u4E00\u4E2A\u7B7E\u540D\u6536\u96C6\u8BF7\u6C42
     - examples: [{example={
  "signerRedirectUri" : "aeiou",
  "signatureId" : "aeiou",
  "signatureFileUri" : "aeiou"
}, contentType=application/json}]
     
     - parameter clientId: (path) \u5BA2\u6237\u7F16\u53F7 
     - parameter body: (body)  (optional)

     - returns: RequestBuilder<SignatureSummary> 
     */
    public class func createSignatureWithRequestBuilder(clientId clientId: String, body: Signature?) -> RequestBuilder<SignatureSummary> {
        var path = "/clients/{clientId}/signatures"
        path = path.stringByReplacingOccurrencesOfString("{clientId}", withString: "\(clientId)", options: .LiteralSearch, range: nil)
        let URLString = SwaggerClientAPI.basePath + path
        
        let parameters = body?.encodeToJSON() as? [String:AnyObject]

        let requestBuilder: RequestBuilder<SignatureSummary>.Type = SwaggerClientAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "POST", URLString: URLString, parameters: parameters, isBody: true)
    }

    /**
     
     \u83B7\u53D6\u7B7E\u7F72\u56FE\u7247
     
     - parameter clientId: (path) \u5E94\u7528\u7CFB\u7EDF\u7F16\u53F7 
     - parameter signatureId: (path) \u7B7E\u540D\u7F16\u53F7 
     - parameter completion: completion handler to receive the data and the error objects
     */
    public class func getSignature(clientId clientId: String, signatureId: String, completion: ((data: SignatureFile?, error: ErrorType?) -> Void)) {
        getSignatureWithRequestBuilder(clientId: clientId, signatureId: signatureId).execute { (response, error) -> Void in
            completion(data: response?.body, error: error);
        }
    }


    /**
     
     \u83B7\u53D6\u7B7E\u7F72\u56FE\u7247
     
     - GET /clients/{clientId}/signatures/{signatureId}
     - \u83B7\u53D6\u7B7E\u7F72\u56FE\u7247
     - examples: [{example={
  "imagePngBase64" : "aeiou"
}, contentType=application/json}]
     
     - parameter clientId: (path) \u5E94\u7528\u7CFB\u7EDF\u7F16\u53F7 
     - parameter signatureId: (path) \u7B7E\u540D\u7F16\u53F7 

     - returns: RequestBuilder<SignatureFile> 
     */
    public class func getSignatureWithRequestBuilder(clientId clientId: String, signatureId: String) -> RequestBuilder<SignatureFile> {
        var path = "/clients/{clientId}/signatures/{signatureId}"
        path = path.stringByReplacingOccurrencesOfString("{clientId}", withString: "\(clientId)", options: .LiteralSearch, range: nil)
        path = path.stringByReplacingOccurrencesOfString("{signatureId}", withString: "\(signatureId)", options: .LiteralSearch, range: nil)
        let URLString = SwaggerClientAPI.basePath + path
        
        let nillableParameters: [String:AnyObject?] = [:]
        let parameters = APIHelper.rejectNil(nillableParameters)

        let requestBuilder: RequestBuilder<SignatureFile>.Type = SwaggerClientAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "GET", URLString: URLString, parameters: parameters, isBody: true)
    }

}
